### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by FranklinMCA** [MrCrayfish/MrCrayfishVehicleMod#296]
[crash-2020-06-23_19.42.45-client.txt](https://github.com/MrCrayfish/MrCrayfishVehicleMod/files/4821021/crash-2020-06-23_19.42.45-client.txt)

**Comment by AzazelMango** [comment]
This is my current error as well. Plz halp Cray!

Edit 1: Since we both have the mod TexFix, Ima remove it and check of it works again.

Edit 2: I have go thru backdating obfuscate, removing new mods, backdating vehicles and a combination. None of which except going back to vehicles v0.38.1. This is very weird for I was using 0.41.0 in my previous modpack version and it doesnt work anymore here either. Im at a loss for what to do. I tried.

**Comment by MrCrayfish** [comment]
I remember this being caused by another mod. Remove Pollution of the Realms. Also I no longer support 1.12.2
