### ISSUE TITLE
copilot bug

### ISSUE THREAD

**Issue by mercadanteus** [MrCrayfish/MrCrayfishVehicleMod#48]
There's a bug, when you are co-pilot and the car is climbing, you go through the earth, unlike the driver you can't see nothing cause you go underground until the vehicle stops going up, and sometimes until it goes down,

**Comment by samuelh2005** [comment]
Still a thing now:(

**Comment by MrCrayfish** [comment]
Unfortunately this is just desync. It is less common in the upcoming update since I've reworked physics. The main problem is that Minecraft's movement handling isn't that great for fast entities (hence why minecarts have a speed cap). The vehicles in the mod go faster than the minecart speed cap at the trade off of faster entities but potential desync (but most of the time it doesn't happen).
