### ISSUE TITLE
Lawn mower no fuel

### ISSUE THREAD

**Issue by RyanCR03** [MrCrayfish/MrCrayfishVehicleMod#83]
![2018-12-12_17 43 06](https://user-images.githubusercontent.com/32957560/49905965-86050d80-fe35-11e8-85df-f09e5adf6780.png)
the lawn mower has no fuel port (btw i put a resource pack on)

**Comment by RyanCR03** [comment]
also the other side has no port either

**Comment by kendragonrider** [comment]
I have checked on top below and all over there is no fuel port and for the 64x and other materials it requires it should not have such a bad issue making it unusable in survival it should ever not be craftable or have a fuel port. I was going to use the mower for harvesting stuff on my farm luckily i checked in creative before crafting it and because both the trailers and seeders have stuff taken by hoppers i cant use hoppers to collect the stuff so i cant harvest from my farm without 20 minutes of work. Honestly im disappointed such a glaring issue on a mod so great can really bring it down.

**Comment by Heisler70** [comment]
Having same issue

**Comment by MrCrayfish** [comment]
Fixed in latest version
